[package]
name = "srcs-render"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
lexicon-core.workspace = true
srcs-reader.workspace = true
html-preserve.workspace = true
serde.workspace = true
serde_json.workspace = true

[lints]
workspace = true
